-- Run ONCE in Supabase: SQL Editor > New query > paste this > Run.

create table if not exists public.users (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  email       text not null unique,
  phone       text not null,
  salt        text not null,
  hash        text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.requests (
  id             uuid primary key default gen_random_uuid(),
  number         bigint generated by default as identity unique,
  created_at     timestamptz not null default now(),
  status         text not null default 'New',
  notes          text not null default '',
  user_id        uuid references public.users(id) on delete set null,
  name           text not null,
  phone          text not null,
  email          text not null default '',
  service_slug   text not null,
  service_title  text not null,
  budget         text not null default '',
  deadline       text not null default '',
  message        text not null
);

create index if not exists requests_user_id_idx    on public.requests (user_id);
create index if not exists requests_created_at_idx on public.requests (created_at desc);

-- Lock the tables. With RLS on and no policies, the public (publishable) key
-- can read nothing. Only your server, using the secret key, can reach the data.
alter table public.users    enable row level security;
alter table public.requests enable row level security;
